    <footer>
        <ul>
            <li><a href="https://github.com/106566951/Web-Technology-Project-Part-1">Github Repository</a></li>
            <li><a href="https://106566951.github.io/Web-Technology-Project-Part-1/">Github Pages Site</a></li>
            <li><a href="https://greengrid.atlassian.net/jira/software/projects/GG/boards/2">Jira Project</a></li>
            <li>Email: <a href="mailto:info@greengridbusiness.com">info@greengridbusiness.com</a></li>
        </ul>
    </footer>
</body>
</html>