<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="The Coders">
    <meta name="description" content="This is the about page for the Green Grid website, providing information about the company and the developers who contributed to the project.">
    <meta name="keywords" content="Green Grid, renewable energy, about us, developers, contributions">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Green Grid</title>
    <link rel="stylesheet" href="styles/style.css">
    </head>
<body>
    <nav>
        <ul>
            <li><img src="styles/images/greengrid_logo.png" width="50" height="45" alt="greengrid_logo"></li>
            <li><h1>GREEN GRID</h1></li>
            <li><a class="navlink" href="index.php">Home Page</a></li>
            <li><a class="navlink" href="apply.php">Apply Now</a></li>
            <li><a class="navlink" href="jobs.php">Job Listings</a></li>
            <li><a class="navlink" href="about.php">About Us</a></li>
            <li><a class="navlink" href="login.php">Employee Log-in</a></li>
        </ul>
    </nav>