<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="The Coders">
    <meta name="description" content="This is the about page for the Green Grid website, providing information about the company and the developers who contributed to the project.">
    <meta name="keywords" content="Green Grid, renewable energy, about us, developers, contributions">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Green Grid</title>
    <link rel="stylesheet" href="styles/style.css">
    </head>
